use AurionPro
select * from customer
select * from MARCHANT

CREATE TABLE BANK_MASTER(
 NAME VARCHAR(20) PRIMARY KEY,
 PWD VARCHAR(20),
 BALANCE FLOAT ,
 CONSTRAINT MINBAL CHECK(BALANCE >=500)
)

CREATE TABLE BANK_TRANSACTION(
NAME VARCHAR(20) FOREIGN KEY REFERENCES BANK_MASTER(NAME),
AMOUNT FLOAT,
TYPE CHAR,
TDATE VARCHAR(20),
CONSTRAINT CHECK_TYPE CHECK(TYPE='W' OR TYPE='D')
)

INSERT INTO BANK_MASTER VALUES('ABC','ABC@',1000);
INSERT INTO BANK_MASTER VALUES('XYZ','XYZ@',100);

INSERT INTO BANK_TRANSACTION VALUES('ABC',500,'D','12/07/2019');
INSERT INTO BANK_TRANSACTION VALUES('ABC',500,'A','12/07/2019');

select * from BANK_MASTER
select * from BANK_TRANSACTION

select * from BANK_TRANSACTION where NAME='ABC';