CREATE TABLE DEPT (
 DEPTNO              integer NOT NULL,
 DNAME               varchar(14),
 LOC                 varchar(13),
 CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP (
 EMPNO               integer NOT NULL,
 ENAME               varchar(10),
 JOB                 varchar(9),
 MGR                 integer CONSTRAINT EMP_SELF_KEY REFERENCES EMP (EMPNO),
 HIREDATE            DATEtime,
 SAL                 money,
 COMM                money,
 DEPTNO              integer NOT NULL,
 CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
 CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-81',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-81',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-81',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-81',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-81',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-81',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-82',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-83',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);

select * from EMP
select * from DEPT

--ORDER BY NAME 
SELECT * FROM EMP ORDER BY ENAME;

--SALARY BETWEEN 2000 AND 5000
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 5000;

--EMPS WHOES DEPT=10
SELECT * FROM EMP WHERE DEPTNO=10

--EMPS WHOES DEPT=10 OR 20
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20;

--EMP NAME WHO IS MANAGES
SELECT * FROM EMP WHERE JOB='MANAGER';

--EMPS WHOES JOB=MANAGERS AND DEPTNO=10
SELECT * FROM EMP WHERE JOB='MANAGER' AND DEPTNO=10;

--EMP WHOES COMMISSIN=NULL
SELECT * FROM EMP WHERE COMM IS NULL;

--EMP WITH NAME SAL AND CTC
SELECT ENAME,SAL,(SAL*12+(ISNULL(COMM,0))) AS CTC FROM EMP;

--EMP NAME WITH LOWERCASE
SELECT LOWER(ENAME) AS NAME FROM EMP;

--DISPLAY uniqe DEPTS
SELECT DISTINCT DEPTNO FROM EMP; 

--DISPLAY NAME HIREDATE AND YEAR OF EXPERIANCE
SELECT ENAME,HIREDATE,((YEAR(GETDATE())-YEAR(HIREDATE))) AS EXPERINACE FROM EMP;


--DISPLAY TOP3 SAL EMPS
--SELECT * FROM EMP WHERE SAL IN (SELECT TOP 2 SAL FROM EMP ORDER BY SAL DESC) ORDER BY SAL DESC;
SELECT TOP 3 * FROM EMP ORDER BY SAL DESC;

--DISPLAY ALL EMPS WHOES SCOTT DEPTNO
SELECT * FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');

-- DISPLAY EMPS WHOES JOB IS SAME AS BLAKE
SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME='BLAKE');

--DISPLAY ALL REPORTIES OF KING
SELECT * FROM EMP WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME='KING');

--DISPLAY AVG,COUNT,MIN,MAX ON SAL
SELECT COUNT(ENAME)AS COUNT,AVG(SAL) AS AVG_SAL,MIN(SAL) AS MIN_SAL,MAX(SAL) AS MAX_SAL FROM EMP;

--STORED PROCEDURES

GO
CREATE PROCEDURE DBO.UDP_GIVEHIKE (@ID INT,@PERCENTAGE FLOAT)
AS 
  UPDATE EMP
  SET EMP.SAL=EMP.SAL+EMP.SAL*(@PERCENTAGE/100)
  WHERE EMPNO=@ID;
  SELECT * FROM EMP WHERE EMPNO=@ID
GO

SELECT * FROM EMP

EXEC dbo.UDP_GIVEHIKE @ID=7369,@PERCENTAGE=5;

--METADATA
SELECT * FROM sys.all_objects WHERE name='EMP';

SELECT * FROM sys.procedures;

--FUNCTION MAX SAL
GO
CREATE FUNCTION UDF_MAXSALARIED_EMP()
RETURNS VARCHAR(20)
BEGIN
  RETURN (SELECT ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL)FROM EMP ))
END
GO

SELECT dbo.UDF_MAXSALARIED_EMP()AS EMP

--TRIGGRES ON INSERT
GO
CREATE TRIGGER UDT_UPPERCASE
ON DEPT
INSTEAD OF INSERT,UPDATE
AS
BEGIN
  DECLARE
  @ID INT,
  @DNAME VARCHAR(10),
  @DLOC VARCHAR(20)
  
  SELECT @ID=INSERTED.DEPTNO FROM INSERTED
  SELECT @DNAME=INSERTED.DNAME FROM INSERTED
  SELECT @DLOC=INSERTED.LOC FROM INSERTED
  INSERT INTO DEPT VALUES(@ID,UPPER(@DNAME),UPPER(@DLOC));
  
END

INSERT INTO DEPT VALUES(5,'marketing','pune');
select * from dept;

