USE AurionPro
SELECT * FROM EMP2;

SELECT * FROM sys.all_objects WHERE name='EMP2';
SELECT * FROM sys.columns WHERE object_id=1301579675;

SELECT * FROM sys.indexes WHERE object_id=1445580188;

ALTER TABLE EMP2 ADD CONSTRAINT PL_EMP2 PRIMARY KEY(ID);
SELECT * FROM sys.indexes WHERE object_id=1445580188;

CREATE NONCLUSTERED INDEX EMPINDEX ON EMP2(NAME);

SELECT * FROM EMP2;
INSERT INTO EMP2 VALUES(5,'XYZ');
INSERT INTO EMP2 VALUES(1,'ABC'); 


-- LOG TABLE

CREATE TABLE A_LOG(
ID INT IDENTITY,
LOG_MESSAGE VARCHAR(30)
) 





