SELECT * FROM EMP

--STORED PROCEDURE FOR SALHIKE ON EMP TABLE

CREATE PROCEDURE DBO.UDP_GIVEHIKE @ID INT,@PERCENTAGE FLOAT
AS
 UPDATE EMP 
  SET SAL=(SELECT SAL FROM EMP WHERE EMPNO=@ID)*(@PERCENTAGE/100)
  WHERE EMPNO=@ID;
  SELECT SAL FROM EMP WHERE EMPNO=@ID;
GO

DROP PROCEDURE UDP_GIVEHIKE1
USE AurionPro

 


